# Build Stage
FROM node:14-alpine AS build
WORKDIR /app
COPY . /app/
RUN npm install
RUN npm run build

# Runtime Stage
FROM node:14-alpine
WORKDIR /app
COPY --from=build /app/build/ /app/
COPY --from=build /app/package.json /app/
COPY --from=build /app/package-lock.json /app/
COPY --from=build /app/node_modules/ /app/node_modules/
EXPOSE 3000
CMD ["npm", "start"]

